package criminal_database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import criminal_database.x.*;
import java.sql.SQLException;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author varinder
 */
public class listusers extends javax.swing.JInternalFrame {

    /**
     * Creates new form listadmins
     */
    public listusers() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("List of Users");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Password", "Username", "DOB", "Gender"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Search by Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
 Connection c = null;
        try
        {c=DriverManager.getConnection(x.path+x.place, x.username,x.pass);
        String s;
        
         s="Select * from loguser where username like ?";
        
        
        PreparedStatement x=c.prepareStatement(s);
        x.setString(1, jTextField1.getText().trim()+"%");
        ResultSet p=x.executeQuery();
        
        DefaultTableModel k=(DefaultTableModel) jTable1.getModel();
        k.setRowCount(0);
        while(p.next()){
            
            String name=p.getString("Name");
            String addr=p.getString("Password");
            String username=p.getString("Username");
            Object dob=p.getString("DOB");
            String Gender=p.getString("Gender");
            k.addRow(new Object[]{name,addr,username,dob,Gender});
        
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error : "+e.getMessage());
        }
  finally
        {
            try {
                c.close();
            } catch (SQLException ex) {
           //     Logger.getLogger(Admin_login.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
              
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        Connection c = null;
        try
        {c=DriverManager.getConnection(x.path+x.place, x.username,x.pass);
        String s;
        
         s="Select * from loguser where username like ?";
        
        
        PreparedStatement x=c.prepareStatement(s);
        x.setString(1, jTextField1.getText().trim()+"%");
        ResultSet p=x.executeQuery();
        
        DefaultTableModel k=(DefaultTableModel) jTable1.getModel();
        k.setRowCount(0);
        while(p.next()){
            
            String name=p.getString("Username");
            String addr=p.getString("Password");
            String username=p.getString("Name");
            Object dob=p.getString("DOB");
            String Gender=p.getString("Gender");
            k.addRow(new Object[]{name,addr,username,dob,Gender});
        
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error : "+e.getMessage());
        }
          finally
        {
            try {
                c.close();
            } catch (SQLException ex) {
           //     Logger.getLogger(Admin_login.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
      
    }//GEN-LAST:event_jTextField1FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
