/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminal_database;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author varinder
 */
public class prisonerlist extends javax.swing.JInternalFrame {

    /**
     * Creates new form prisonerlist
     */
    public prisonerlist(String val) {
        initComponents();
         Connection c = null;
        try
        {c=DriverManager.getConnection(x.path+x.place, x.username,x.pass);
        String s;
        
         s="Select * from prisoner where CID=?";
        PreparedStatement x=c.prepareStatement(s);
        x.setString(1, val);
       
        ResultSet p=x.executeQuery();
        
        DefaultTableModel k=(DefaultTableModel) jTable1.getModel();
        k.setRowCount(0);
        while(p.next()){
            String a=p.getString("CID");
            String a1=p.getString("crimes");
            String a2=p.getString("jail");
            Date a3=p.getDate("date");
            String a4=p.getString("servetime");
           
            SimpleDateFormat s1;s1=new SimpleDateFormat("dd-MM-yyyy");
            Calendar c1;
            c1 = Calendar.getInstance();
            c1.setTime(a3);
            
            c1.add(Calendar.YEAR, Integer.parseInt(a4.substring(0,4)));
            c1.add(Calendar.MONTH,Integer.parseInt(a4.substring(5,7)) );
            c1.add(Calendar.DATE,Integer.parseInt(a4.substring(8)) );
            String a5=s1.format(c1.getTime());
            String a6=p.getString("PID");
               
            k.addRow(new Object[]{a,a1,a2,s1.format(a3),a4,a5,a6});
            
                }
        
         s="Select * from newcriminal where CID=?";
        PreparedStatement x1=c.prepareStatement(s);
       x1.setString(1, val);
       
        ResultSet p1=x1.executeQuery();
        if(p1.next())
        {
              String a7=p1.getString("image");
            File f=new File(System.getProperty("user.dir")+"/"+a7);
            Image i=ImageIO.read(f).getScaledInstance(143,123,Image.SCALE_AREA_AVERAGING);
            jLabel9.setIcon(new ImageIcon(i) );
             
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error "+e.getMessage());
        }
          finally
        {
            try {
                c.close();
            } catch (SQLException ex) {
           //     Logger.getLogger(Admin_login.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Criminal ID", "Current Crimes", "Jail", "Started serving on Date", "Time sentenced", "Releasing date", "Prisoner ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(404, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
